services:
  # Sigle api server instance
  - name: sigle-api
    type: web
    env: node
    region: oregon
    plan: Starter
    branch: main
    healthCheckPath: /health
    autoDeploy: true
    buildCommand: cd server; pnpm install --filter=@sigle/server; pnpm run build
    startCommand: cd server; pnpm run start
    domains:
      - api.sigle.io
    buildFilter:
      paths:
        # changes to the frontend dir do not match this pattern
        - server/**
      ignoredPaths:
        # Do not deploy if test file changed
        - server/**/*.test.ts
    envVars:
      - key: APP_URL
        value: 'https://app.sigle.io'
      # Value used to decode the cookies
      - key: NEXTAUTH_URL
        value: 'https://app.sigle.io'
      # Inject Redis connection url from the redis instance
      - key: REDIS_DATABASE_URL
        fromService:
          type: redis
          name: sigle-redis
          property: connectionString
      # Inject Postgres connection url from the redis instance
      - key: PG_DATABASE_URL
        fromDatabase:
          name: sigle-postgres
          property: connectionString

  # Redis database
  - name: sigle-redis
    type: redis
    region: oregon
    plan: Starter
    # only allow internal connections
    ipAllowList: []

  # Postgres database
  - name: sigle-postgres
    region: oregon
    plan: Starter
    postgresMajorVersion: 14
    # only allow internal connections
    ipAllowList: []
