name: Deploy to staging

on:
  push:
    branches:
      # Change the branch name to deploy the current feature branch to staging
      - 'feature/enable-supporter-plan'

jobs:
  deploy-sigle:
    name: Deploy sigle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env file
        run: mv sigle/.env.staging sigle/.env.production
      - uses: superfly/flyctl-actions@1.1
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        with:
          args: 'deploy --config sigle/fly.staging.toml --dockerfile sigle/Dockerfile --remote-only'

  deploy-blog-viewer:
    name: Deploy sigle blog viewer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env file
        run: mv blog-viewer/.env.staging blog-viewer/.env.production
      - uses: superfly/flyctl-actions@1.1
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        with:
          args: 'deploy --config blog-viewer/fly.staging.toml --dockerfile blog-viewer/Dockerfile --remote-only'
